config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
  root to: 'lists#index'
  resources :lists, only: [:index, :show, :new, :create] do
    resources :bookmarks, only: [:new, :create]
  end
  resources :bookmarks, only: [:destroy]

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/bookmark.rb
class Bookmark < ApplicationRecord
  belongs_to :movie
  belongs_to :list

  validates :comment, length: { minimum: 6 }
  validates :movie_id, presence: true, uniqueness: { scope: :list_id }
end

app/models/list.rb
class List < ApplicationRecord
  has_many :bookmarks, dependent: :destroy
  has_many :movies, through: :bookmarks
  
  validates :name, presence: true, uniqueness: true
end

app/models/movie.rb
class Movie < ApplicationRecord
  has_many :bookmarks
  validates :title, presence: true, uniqueness: true
  validates :overview, presence: true, uniqueness: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/bookmarks_controller.rb
class BookmarksController < ApplicationController
  def new
    @list = List.find(params[:list_id])
    @bookmark = Bookmark.new
  end

  def create
    @bookmark = Bookmark.new(bookmark_params)
    @list = List.find(params[:list_id])
    @bookmark.list = @list
    if @bookmark.save
      redirect_to list_path(@list)
    else
      render :new
    end
  end

  def destroy
    @bookmark = Bookmark.find(params[:id])
    @list = @bookmark.list
    @bookmark.destroy
    redirect_to list_path(@list), status: :see_other
  end

  private

  def bookmark_params
    params.require(:bookmark).permit(:movie_id, :comment)
  end


end

app/controllers/lists_controller.rb
class ListsController < ApplicationController
  def index
    @lists = List.all
  end

  def show
    @list = List.find(params[:id])
  end

  def new
    @list = List.new(params[:id])
  end

  def create
    @list = List.new(list_params)
    if @list.save
      redirect_to list_path(@list)
    else
       render :new
    end
  end

  private

  def list_params
    params.require(:list).permit(:name)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bookmarks_helper.rb
module BookmarksHelper
end

app/helpers/lists_helper.rb
module ListsHelper
end

app/views/bookmarks/new.html.erb
<div class='container'>
<h1>Add a movie</h1>
<%= simple_form_for ([@list, @bookmark]) do |f| %>
  <%= f.association :movie %>
  <%= f.input :comment, placeholder: "what do you think of this movie?" %>
  <%= f.submit "Submit bookmark", class: "btn btn-primary" %>
<% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsWatchList</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/lists/index.html.erb
<div class ='container py-5'>
<h1>List of Genres</h1>
  <ul>
    <% @lists.each do |list|%>
      <li><%= link_to list.name, list_path(list) %></li>
    <% end %>
  </ul>

<%= link_to "Add a new list", new_list_path %>
</div>

app/views/lists/new.html.erb
<div class='container'>
<h1>Make a new list</h1>
<%= simple_form_for (@list) do |f| %>
  <%= f.input :name, placeholder: "Drama" %>
  <%= f.submit "Submit list", class: "btn btn-primary" %>
<% end %>
</div>

app/views/lists/show.html.erb
<div class='container m-5'>
<div class='d-flex col-12 container justify-content-center m-3'>
  <h1><%= @list.name %> Show Page</h1>
  </div>
<div class='d-flex col-12 container justify-content-center m-3'>
<% @list.bookmarks.each do |bookmark|%>
  <div class="d-flex row card m-3 g-3" style="width: 20rem;">
    <img src=<%= bookmark.movie.poster_url %> class="card-img-top" alt="...">
    <div class="card-body">
    <h5 class="card-title"><%= link_to bookmark.movie.title, list_path %></h5>
    <p class="card-text"><%= bookmark.movie.overview %></p>
    <%= link_to "Delete from list",
    bookmark_path(bookmark),
    data: {turbo_method: :delete, turbo_confirm: "Are you sure?"} %>

  </div>
</div>
<% end %>
</div>
<div class='d-flex col-12 container justify-content-evenly m-3'>
<%= link_to "Add a movie", new_list_bookmark_path(@list) %>

<%= link_to "Back to list of Genres", lists_path %>
</div>
</div>

app/views/lists/temp.html.erb
<ul>
    <% @list.bookmarks.each do |bookmark|%>
      <h2></h2>
      <p><%= bookmark.movie.overview %></p>
      <p><%= bookmark.movie.poster_url %></p>
      <p><%= bookmark.comment %></p>
      <%= link_to "Delete from list",
        bookmark_path(bookmark),
        data: {turbo_method: :delete, turbo_confirm: "Are you sure?"}
      %>
    <% end %>
  </ul>